Repository princessbook/booktique, pull requests merged in 2024-04, with the labels that each got.

#10 #6 [대연] 레이아웃 설정
  .prettierrc
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/common/Button.tsx
  src/components/footer/page.tsx
  src/components/header/page.tsx
  tailwind.config.ts
  yarn.lock
Labels: 📖HTML&CSS

#11 [현미] : 북클럽 개설 기본 UI 작성 및 DB에 데이터 저장
  src/app/create-bookclub/page.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature

#15 [현미] 북클럽 전체 목록 페이지, 상세 페이지 UI 구현 및 일부 DB 연결
  src/app/bookclubs/detail/[id]/page.tsx
  src/app/bookclubs/page.tsx
  src/utils/time.ts
Labels: 🖥Feature

#16 [승희] : CORS 이슈 해결, 검색 기능 구현
  .gitignore
  next.config.mjs
  package.json
  src/app/api/[keyword]/route.ts
  src/app/api/getBookInfo/[id]/route.ts
  src/app/search/[keyword]/[detail]/page.tsx
  src/app/search/[keyword]/page.tsx
  src/app/search/page.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchResult.tsx
  src/lib/types/BookAPI.ts
  src/utils/bookAPIs/bookAPI.ts
  tailwind.config.ts
  yarn.lock
Labels: 🖥Feature, 💻API

#17 [철균] : 로그인, 회원가입구현
  middleware.ts
  package-lock.json
  package.json
  src/app/auth/callback/route.ts
  src/app/login/action.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/private/page.tsx
  src/app/register/page.tsx
  src/app/test/page.tsx
  src/hooks/clientSession.ts
  src/hooks/fetchDB.ts
  src/hooks/serverSession.ts
  src/hooks/useInput.ts
  src/hooks/useLogin.ts
  src/lib/supabase.ts
  src/lib/utils.ts
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
  yarn.lock
Labels: 🖥Feature, ⚙Settings

#18 [대연] 레이아웃수정 , 내 북클럽 페이지 UI
  next.config.js
  next.config.mjs
  public/booktiqueread.png
  public/mybook.png
  src/app/layout.tsx
  src/app/myclub/page.tsx
  src/app/page.tsx
  src/common/Button.tsx
  src/common/LoadingOverlay.tsx
Labels: 🖥Feature, 📖HTML&CSS

#21 [철균] : 로그인, 회원가입 로직변경
  middleware.ts
  src/app/auth/callback/route.ts
  src/app/auth/confirm/route.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/private/page.tsx
  src/app/register/page.tsx
  src/app/test/page.tsx
  src/hooks/clientSession.ts
  src/hooks/fetchDB.ts
  src/hooks/serverSession.ts
  src/lib/supabase.ts
Labels: 🖥Feature, ⚙Settings, 🔨BugFix

#23 [예린] - 마이페이지 기능 구현
  next.config.js
  next.config.mjs
  public/default_img.png
  src/app/create-bookclub/page.tsx
  src/app/mypage/page.tsx
  src/components/footer/page.tsx
  src/components/mypage/MyBook.tsx
  src/components/mypage/MyBookClub.tsx
  src/components/mypage/MySentencesStore.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileDetail.tsx
  src/utils/userAPIs/Fns.ts
  src/utils/userAPIs/authAPI.ts
  src/utils/userAPIs/storageAPI.ts
Labels: 🖥Feature

#25 [현미] 북클럽 개설한 유저 추가, 참가한 유저 추가하는 기능 구현 및 관련 UI 변경
  src/app/bookclubs/GetClubMembersNumber.tsx
  src/app/bookclubs/detail/[id]/GetClubMember.tsx
  src/app/bookclubs/detail/[id]/JoinBtn.tsx
  src/app/bookclubs/detail/[id]/page.tsx
  src/app/bookclubs/page.tsx
  src/app/create-bookclub/page.tsx
  src/common/constants/tableNames.ts
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#35 [에린] - 마이페이지 아바타 렌더링 문제는 해결
  package.json
  src/app/layout.tsx
  src/app/myclub/page.tsx
  src/app/mypage/page.tsx
  src/app/provider.tsx
  src/components/footer/page.tsx
  src/components/mypage/MyBookClub.tsx
  src/components/mypage/ProfileDetail.tsx
  src/utils/userAPIs/Fns.ts
  src/utils/userAPIs/authAPI.ts
  yarn.lock
Labels: 🖥Feature, 🔨BugFix

#37 [현미] 퀴즈 작성 UI 생성 및 기능 추가
  package.json
  src/app/bookclubs/detail/[id]/GetClubMember.tsx
  src/app/create-quiz/QuizAnswer.tsx
  src/app/create-quiz/QuizQuestion.tsx
  src/app/create-quiz/page.tsx
  yarn.lock
Labels: 🖥Feature, 📖HTML&CSS

#39 [대연] - 책 읽기 페이지 읽기 기능 추가
  public/booktiquereadblue.png
  public/booktiquereadwhite.png
  src/app/myclub/layout.tsx
  src/app/myclub/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
  src/components/footer/page.tsx
Labels: 🖥Feature

#40 [승희] : 책 검색기능 모달로 변경
  package.json
  src/app/modaltest/page.tsx
  src/app/search/page.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchModal.tsx
  src/components/search/SearchResult.tsx
  src/lib/types/BookAPI.ts
  src/utils/bookAPIs/bookAPI.ts
  yarn.lock
Labels: 🎨refactoring

#46 [철균] - 전체style수정및 마이페이지 로그아웃기능및 login시 내북클럽으로 리다이렉트
  src/app/layout.tsx
  src/app/login/action.ts
  src/app/login/page.tsx
  src/app/register/page.tsx
  src/common/Input.tsx
  src/components/footer/page.tsx
  src/components/mypage/ProfileDetail.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/SelectForm.tsx
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#50 [예린] - 내 북클럽 활동 홈 탭 구현
  src/app/myclubinfo/page.tsx
  src/app/mypage/page.tsx
  src/components/footer/page.tsx
  src/components/login/LoginForm.tsx
  src/components/myclubinfo/Board.tsx
  src/components/myclubinfo/HomeTab.tsx
  src/components/myclubinfo/NonMyClub.tsx
  src/components/myclubinfo/SentenceStorage.tsx
  src/components/mypage/MyBook.tsx
  src/components/mypage/MyBookClub.tsx
  src/components/mypage/MySentencesStore.tsx
  src/components/mypage/ProfileDetail.tsx
  src/utils/userAPIs/Fns.ts
  src/utils/userAPIs/authAPI.ts
  tailwind.config.ts
Labels: 🖥Feature

#51 [대연] - #41 북클럽 책읽기 버튼 클릭시 DB저장 및 북클럽에 참가한 멤버출력
  package.json
  src/app/readbook/ClubList.tsx
  src/app/readbook/ProgressBar.tsx
  src/app/readbook/ReadButton.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/layout.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
  src/lib/types/supabase.ts
  yarn.lock
Labels: 🖥Feature

#53 [현미] : 북클럽에 도서 정보 추가
  src/app/bookclubs/ClubAdminProfile.tsx
  src/app/bookclubs/[id]/page.tsx
  src/app/bookclubs/create/page.tsx
  src/app/bookclubs/page.tsx
  src/components/footer/page.tsx
  src/components/search/SearchModal.tsx
  src/components/search/SearchResult.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature, 📖HTML&CSS

#54 [철균] - 로그인(구글,카카오)인증 구현
  public/login_kakao.png
  public/logo_asset.png
  public/logo_google.png
  public/sns.png
  src/app/auth/callback/route.ts
  src/app/login/page.tsx
  src/app/nickname/page.tsx
  src/app/page.tsx
  src/app/private/page.tsx
  src/app/register/avatar/page.tsx
  src/app/register/page.tsx
  src/app/test/page.tsx
  src/common/Input.tsx
  src/components/login/LoginForm.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/SelectForm.tsx
  src/utils/nicknameGenerator.ts
  src/utils/userAPIs/Fns.ts
Labels: 🖥Feature, 🔨BugFix

#58 [fix, feat]: 마이페이지, 홈 탭 구현중
  src/app/myclubinfo/page.tsx
  src/app/mypage/page.tsx
  src/components/myclubinfo/ClubBook.tsx
  src/components/myclubinfo/HomeTab.tsx
  src/components/myclubinfo/Members.tsx
  src/components/myclubinfo/ProgressBar.tsx
  src/components/myclubinfo/SentenceStorage.tsx
  src/components/mypage/ProfileDetail.tsx
  src/utils/userAPIs/authAPI.ts
Labels: 🖥Feature, 🔨BugFix

#59 [대연] : #52
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/EndButton.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/layout.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature, 📖HTML&CSS

#61 [대연] - #60 : 슬라이드,ui 수정, 책읽기 종료하기클릭시 기록할 수 있는 페이지 이동 및 데이터 받는 로직 완료, 책 읽기 종료시 db업데이트 추가 , 페이지ui기본 세팅
  src/app/bookclubs/ClubAdminProfile.tsx
  src/app/globals.css
  src/app/readbook/ClubList.tsx
  src/app/readbook/ProgressBar.tsx
  src/app/readbook/ReadButton.tsx
  src/app/readbook/[id]/EndButton.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/BookInfo.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/page.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
Labels: 🖥Feature, 📖HTML&CSS

#62 [철균] - 로그인 로직진행중
  public/close_input.png
  public/login_logo.png
  src/app/login/page.tsx
  src/app/nickname/page.tsx
  src/app/register/avatar/page.tsx
  src/app/register/page.tsx
  src/common/Input.tsx
  src/components/login/LoginForm.tsx
  src/components/mypage/ProfileDetail.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/register/RegisterForm.tsx
Labels: 📖HTML&CSS, 🔊help wanted

#67 [현미] : 북클럽 페이지 잔버그 수정
  src/app/bookclubs/ClubAdminProfile.tsx
  src/app/bookclubs/ClubMembersCount.tsx
  src/app/bookclubs/[id]/BookClubCSR.tsx
  src/app/bookclubs/[id]/ClubMemberProfile.tsx
  src/app/bookclubs/[id]/JoinAndResignBtn.tsx
  src/app/bookclubs/[id]/JoinBtn.tsx
  src/app/bookclubs/[id]/ResignBtn.tsx
  src/app/bookclubs/[id]/page.tsx
  src/app/bookclubs/create/page.tsx
  src/app/bookclubs/page.tsx
Labels: 🔨BugFix

#70 [대연]-#65
  public/badge.png
  public/close_read.png
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/EndButton.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/BookInfo.tsx
  src/app/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/SaveProgressBar.tsx
  src/app/readbook/[id]/[save]/page.tsx
  src/app/readbook/[id]/layout.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature, 📖HTML&CSS, 🎨refactoring

#71 [철균] - nickname페이지 삭제및 회원가입로직변경중
  src/app/auth/callback/route.ts
  src/app/globals.css
  src/app/myclubinfo/page.tsx
  src/app/mypage/page.tsx
  src/app/nickname/page.tsx
  src/app/register/[id]/page.tsx
  src/app/register/avatar/page.tsx
  src/app/register/page.tsx
  src/components/login/LoginForm.tsx
  src/components/myclubinfo/SentenceModal.tsx
  src/components/myclubinfo/SentenceStorage.tsx
  src/components/myclubinfo/SentenceUser.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/SelectForm.tsx
  src/lib/types/supabase.ts
  src/utils/userAPIs/authAPI.ts
  tailwind.config.ts
Labels: 📖HTML&CSS, 🔨BugFix

#73 [철균] - 문장저장소기능추가
  src/app/nickname/page.tsx
  src/components/myclubinfo/SentenceStorage.tsx
Labels: 🖥Feature

#76 [철균] : 로그인 다시action.ts에 연결
  public/closeInput.svg
  public/snsTitle.png
  src/app/login/action.ts
  src/app/register/avatar/page.tsx
  src/common/Input.tsx
  src/components/login/LoginForm.tsx
  src/components/register/RegisterForm.tsx
Labels: 🔨BugFix

#78 [대연] -#72 css수정
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/page.tsx
  src/app/readbook/page.tsx
Labels: 📖HTML&CSS

#80 [철균]- 회원가입,nickname,avatar폴더변경및 toast창 만들기 및 validation
  public/fail.svg
  public/success.svg
  src/app/login/page.tsx
  src/app/register/[id]/avatar/page.tsx
  src/app/register/[id]/page.tsx
  src/common/ToastUi.tsx
  src/components/login/LoginForm.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/register/RegisterForm.tsx
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#82 [mod]: tailwind.config.ts수정 , [fix] : 퀴즈 탭 추가
  src/app/myclubinfo2/page.tsx
  src/components/myclubinfo/HomeTab.tsx
  src/components/myclubinfo/Members.tsx
  src/components/myclubinfo2/HomeTab.tsx
  src/components/myclubinfo2/Members.tsx
  src/components/mypage/LogoutButton.tsx
  src/components/mypage/MyBookClub.tsx
  src/components/mypage/MySentencesStore.tsx
  src/components/mypage/ProfileDetail.tsx
  src/utils/userAPIs/authAPI.ts
  tailwind.config.ts
Labels: 📖HTML&CSS

#83 [현미]: 책읽기에 퀴즈 Create,Read 기능 추가
  src/app/create-quiz/page.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/components/quiz/QuizAnswer.tsx
  src/components/quiz/QuizContainer.tsx
  src/components/quiz/QuizModal.tsx
  src/components/quiz/QuizQuestion.tsx
  src/components/quiz/QuizShortAnswer.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature, 📖HTML&CSS

#85 [철균] - 문장저장소 선택삭제 및 저장시에 toastui추가
  src/app/globals.css
  src/app/layout.tsx
  src/app/myclubinfo/layout.tsx
  src/app/myclubinfo2/page.tsx
  src/common/ToastUi.tsx
  src/components/myclubinfo/Members.tsx
  src/components/myclubinfo2/SentenceModal.tsx
  src/components/myclubinfo2/SentenceStorage.tsx
  src/components/myclubinfo2/SentenceUser.tsx
  src/components/nickname/MyNicknameForm.tsx
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#87 [대연]-#79 [feat] - 타이머 기능추가하기 , [fix] - 디자인 수정
  src/app/readbook/ClubList.tsx
  src/app/readbook/ProgressBar.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/SaveProgressBar.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
  src/app/readbook/[id]/[save]/page.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/page.tsx
Labels: 🖥Feature, 📖HTML&CSS

#88 #86 [feat] : 내 북클럽 찾기에 퀴즈 아카이빙 추가, 퀴즈 유효성 검사 추가
  src/app/myclubinfo2/page.tsx
  src/components/myclubinfo2/QuizArchiving.tsx
  src/components/quiz/QuizAnswer.tsx
  src/components/quiz/QuizModal.tsx
Labels: 🖥Feature, 📖HTML&CSS

#95 [철균] - 문장저장소 삭제후에 버튼바로 바뀌게
  src/components/myclubinfo2/SentenceStorage.tsx
Labels: 🖥Feature

#96 [승희] : 북클럽 자유게시판 구현
  src/app/myclubinfo2/board/detail/[postId]/page.tsx
  src/app/myclubinfo2/board/posting/[postId]/page.tsx
  src/components/myclubinfo/Board.tsx
  src/components/myclubinfo2/board/Board.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
  src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
  src/utils/postAPIs/postAPI.ts
Labels: 🖥Feature

#97 [철균] - 회원가입후에 페이지 라우팅(mypage) , 닉네임-프로필이미지
  src/app/register/set-nickname/page.tsx
  src/app/register/set-profile-image/page.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/register/RegisterForm.tsx
Labels: 🖥Feature, ✔Deploy

#98 [Design]: 내 북클럽 Members 디자인 수정, [fix]: 종료된 북클럽 안나오게 수정
  src/app/myclubinfo2/page-client.tsx
  src/components/myclubinfo2/ClubBook.tsx
  src/components/myclubinfo2/HomeTab.tsx
  src/components/myclubinfo2/Members.tsx
  src/components/mypage/MyBookClub.tsx
  src/store/zustandStore.ts
  src/utils/userAPIs/authAPI.ts
Labels: 📖HTML&CSS, 🔨BugFix

#99 [현미] - 북클럽 찾기 UI 변경 및 내북클럽에 퀴즈아카이빙 추가
  src/app/bookclubs/ClubSearch.tsx
  src/app/bookclubs/page.tsx
  src/app/myclubinfo2/page-client.tsx
  src/common/constants/bookCategories.ts
  tailwind.config.ts
Labels: 🖥Feature, 📖HTML&CSS

#102 [대연] - #91 [fix]:책읽기 페이지 버그수정, 책읽기 슬라이드 디자인변경
  src/app/bookclubs/[id]/JoinBtn.tsx
  src/app/dy/ClubList.tsx
  src/app/dy/page.tsx
  src/app/dy1/page.tsx
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#104 [fix]:마이페이지 프로필사진 선택안하면 수정 안되는 문제 해결
  src/app/globals.css
  src/app/readbook/ClubList.tsx
  src/components/myclubinfo2/Members.tsx
  src/components/mypage/ProfileDetail.tsx
  src/store/zustandStore.ts
Labels: 🔨BugFix

#106 [철균] - 채팅참여,현재 채팅방을 이용하고잇는 사용자 수
  1.8.1
  package-lock.json
  package.json
  src/app/chat/[id]/page.tsx
  src/app/myclubinfo2/page-client.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/page.tsx
  src/components/realtime/ChatComponent.tsx
  src/components/realtime/ChatInput.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/Message.tsx
  src/lib/types/supabase.ts
  src/store/InitMessages.tsx
  src/store/InitUser.tsx
  src/store/messages.ts
  src/store/user.ts
  tsconfig.json
  yarn.lock
Labels: 🖥Feature

#109 #56 [승희]: 자유게시판 구현
  src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
  src/utils/postAPIs/postAPI.ts
Labels: 🖥Feature

#111 [fix] : 현재 진행중인 내 북클럽 안나오는 문제
  src/app/myclubinfo/layout.tsx
  src/app/myclubinfo2/page-client.tsx
  src/app/mypage/[userId]/page.tsx
  src/app/mypage/page.tsx
  src/app/readbook/ClubList.tsx
  src/components/myclubinfo2/HomeTab.tsx
  src/components/myclubinfo2/NonMyClub.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileDetail.tsx
Labels: 🔨BugFix

#115 [대연] - #108
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
  src/app/readbook/[id]/page.tsx
Labels: 🖥Feature, 🔨BugFix

#118 #117 [fix]-로그인여부에 따라 루트page 리다이렉트
  src/app/page.tsx
Labels: 🔨BugFix

#123 [철균] : 안쓰는 파일 제거 및 console.log 정리
  src/app/chat/[id]/page.tsx
  src/app/nickname/page.tsx
  src/app/register/page.tsx
  src/app/register/set-nickname/page.tsx
  src/app/register/set-profile-image/page.tsx
  src/common/ToastUi.tsx
  src/components/login/LoginForm.tsx
  src/components/myclubinfo2/SentenceModal.tsx
  src/components/myclubinfo2/SentenceStorage.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/realtime/ChatComponent.tsx
  src/components/realtime/ChatInput.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/Message.tsx
  src/components/register/SelectForm.tsx
  src/lib/types/supabase.ts
  src/store/messages.ts
  src/utils/supabase/middleware.ts
Labels: 🔨BugFix

#124 [승희]: 에러 수정
  src/app/myclubinfo2/board/detail/[postId]/page.tsx
  src/components/myclubinfo2/board/Board.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
Labels: 🔨BugFix, 🎨refactoring

#126 [대연] - #122 [fix]-빌드확인용 콘솔제거 및 파일제거
  public/noclub.png
  src/app/dy/ClubList.tsx
  src/app/dy/page.tsx
  src/app/dy1/page.tsx
  src/app/globals.css
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
  src/app/readbook/[id]/[save]/page.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/layout.tsx
  src/app/readbook/page.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#131 [예린] - myClubInfo 페이지랑 컴포넌트 지우기, 북클럽 없을때 화면 디자인 수정
  src/app/myclubinfo/[id]/home/page.tsx
  src/app/myclubinfo/[id]/sentencestorage/page.tsx
  src/app/myclubinfo/layout.tsx
  src/app/myclubinfo/page.tsx
  src/app/myclubinfo2/page-client.tsx
  src/common/Button.tsx
  src/components/myclubinfo/ClubBook.tsx
  src/components/myclubinfo/HomeTab.tsx
  src/components/myclubinfo/Members.tsx
  src/components/myclubinfo/NonMyClub.tsx
  src/components/myclubinfo/SentenceModal.tsx
  src/components/myclubinfo/SentenceStorage.tsx
  src/components/myclubinfo/SentenceUser.tsx
  src/components/myclubinfo2/HomeTab.tsx
  src/components/myclubinfo2/NonMyClub.tsx
  src/components/mypage/ProfileDetail.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#136 [철균] - build오류 해결
  src/app/auth/callback/route.ts
  src/app/chat/[id]/ChatInput.tsx
  src/utils/supabase/server.ts
Labels: 🔨BugFix

#137 [대연] - #127 [fix] - 화면에 있는 상황에만 타이머기능 동작, 디자인 수정
  src/app/readbook/ClubList.tsx
  src/app/readbook/ProgressBar.tsx
  src/app/readbook/[id]/EndModal.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
  src/app/readbook/[id]/page.tsx
  src/app/readbook/page.tsx
  src/components/realtime2/ClubPresence.tsx
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#143 [철균] - #141 [fix] : toast message나오기전에 모달닫히는거 해결
  src/app/register/set-profile-image/page.tsx
  src/components/myclubinfo2/SentenceModal.tsx
Labels: 🔨BugFix

#145 [대연] - #144 [fix,design] - footer와 책읽기 css 수정, 책읽기 타이머 높이 수정
  public/footer_mybookclub.png
  public/footer_mybookclubactive.png
  public/footer_mypage.png
  public/footer_mypageactive.png
  public/footer_readbook.png
  public/footer_readbookactive.png
  public/footer_searchclub.png
  public/footer_searchclubactive.png
  src/app/layout.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
  src/common/ToastUi.tsx
  src/components/footer/page.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#147 [철균] - toastui애니메이션, realtime채팅창, 로그인실패시 alert
  src/app/globals.css
  src/app/login/action.ts
  src/common/Input.tsx
  src/common/ToastUi.tsx
  src/components/login/LoginForm.tsx
  src/components/myclubinfo2/SentenceModal.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/Message.tsx
  src/components/realtime/OtherMessage.tsx
  src/components/register/RegisterForm.tsx
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#149 [승희] - Board 유효성 검사 추가, postlist css 변경
  package.json
  src/app/myclubinfo2/board/posting/[postId]/page.tsx
  src/components/myclubinfo2/board/Board.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleTimeStamp.tsx
  src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
  src/hooks/Board/useRelativeTime.tsx
  src/lib/types/supabase.ts
  tailwind.config.ts
  yarn.lock
Labels: 📖HTML&CSS, 🎨refactoring

#151 [예린] - 내 북클럽 홈 탭 디자인 수정중 ,마이페이지 디자인 수정중
  src/app/myclubinfo2/page-client.tsx
  src/app/readbook/ClubList.tsx
  src/app/readbook/ProgressBar.tsx
  src/components/myclubinfo2/ClubBook.tsx
  src/components/myclubinfo2/HomeTab.tsx
  src/components/myclubinfo2/Members.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileDetail.tsx
  src/store/zustandStore.ts
  src/utils/supabase/server.ts
Labels: 📖HTML&CSS

#152 [철균] - #148 [feat,fix]:채팅 최신순으로 정렬 및 scrollbar두개중복 하나로 해결
  src/app/bookclubs/ClubAdminProfile.tsx
  src/app/chat/[id]/ChatInput.tsx
  src/app/globals.css
  src/components/realtime/ListMessages.tsx
  src/components/realtime/Message.tsx
  src/components/realtime/OtherMessage.tsx
Labels: 🖥Feature, 📖HTML&CSS

#153 [현미] - 퀴즈 정답제출하기 기능 추가
  package.json
  src/components/quiz/QuizAnswer.tsx
  src/components/quiz/QuizContainer.tsx
  src/components/quiz/QuizModal.tsx
  src/components/quiz/QuizQuestion.tsx
  src/components/quiz/QuizShortAnswer.tsx
  yarn.lock
Labels: 🖥Feature, 📖HTML&CSS

#157 [승희]: 글쓰기 스타일 추가, 댓글 개발중
  src/app/myclubinfo2/board/detail/[postId]/page.tsx
  src/app/myclubinfo2/board/posting/[postId]/page.tsx
  src/components/myclubinfo2/board/Board.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
  src/components/myclubinfo2/board/boardDetail/BoardDetailArticle.tsx
  src/utils/api/postCommentAPIs/commentAPI.ts
Labels: 🖥Feature, 📖HTML&CSS, 💻API

#162 [예린] - 북클럽 최신순 정렬
  src/components/mypage/AllMyBookClubs.tsx
  src/components/mypage/MyBookClub.tsx
Labels: 🔨BugFix

#166 [승희]: 댓글 기능 구현, 스타일 추가
  src/app/myclubinfo2/board/detail/[postId]/page.tsx
  src/app/myclubinfo2/board/posting/[postId]/page.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleComment.tsx
  src/components/myclubinfo2/board/boardDetail/ArticleCommentInput.tsx
  src/lib/types/supabase.ts
  src/utils/api/postCommentAPIs/commentAPI.ts
Labels: 🖥Feature, 📖HTML&CSS, 💻API

#171 [대연] - #170 [fix,feat] - 새로고침시 푸터 클릭해제 수정, 알람테스트
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/MemberList.tsx
  src/app/readbook/[id]/[save]/Timer.tsx
  src/app/readbook/[id]/page.tsx
  src/components/footer/page.tsx
  src/lib/types/supabase.ts
Labels: 🖥Feature, 📖HTML&CSS, 🔨BugFix

#186 [현미] Feature/#183 북클럽 찾기 페이지 스타일 및 기능 추가
  src/app/bookclubs/ClubSearch.tsx
  src/app/bookclubs/page.tsx
  src/app/layout.tsx
Labels: 🖥Feature, 📖HTML&CSS

#190 [현미] - [fix/#187] : 퀴즈 객관식 답안 최소입력 개수 제한, 자잘한 버그 및 스타일 수정
  src/components/quiz/QuizAnswer.tsx
  src/components/quiz/QuizContainer.tsx
  src/components/quiz/QuizModal.tsx
  src/components/quiz/QuizQuestion.tsx
  src/components/quiz/QuizShortAnswer.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#192 [대연] - #170 [fix] - css수정, 모임시작 로직 변경,책 읽기 버튼 주석처리, 카드 클릭시 이동
  src/app/readbook/ClubList.tsx
  src/app/readbook/[id]/BookInfo.tsx
  src/app/readbook/[id]/EndButton.tsx
  src/app/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/readbook/[id]/[save]/SaveCard.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#194 [현미] Fix/#191 퀴즈 버그 및 스타일 수정
  src/components/myclubinfo2/QuizArchiving.tsx
  src/components/quiz/MultipleChoiceQuizComponent.tsx
  src/components/quiz/QuizContainer.tsx
  src/components/quiz/ShortQuizComponent.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#201 #172
  src/app/myclubinfo2/page-client.tsx
  src/app/mypage/mybookclubs/page.tsx
  src/app/mypage/page.tsx
  src/components/mypage/AllMyBookClubs.tsx
  src/components/mypage/ProfileDetail.tsx
  src/store/zustandStore.ts
Labels: 🔨BugFix

#204 [철균] - 로그인,회원가입 css문제해결 및 문장공유하기 줄바꿈해결
  src/app/(navigationBar)/layout.tsx
  src/app/chat/[id]/page.tsx
  src/components/myclubinfo2/SentenceStorage.tsx
Labels: ✔Deploy, 🔨BugFix

#212 [철균] : 이슈사항들 해결하기
  src/app/globals.css
  src/common/Input.tsx
  src/components/myclubinfo2/SentenceStorage.tsx
  src/components/nickname/MyNicknameForm.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/register/RegisterForm.tsx
  src/utils/api/authAPI.ts
  src/utils/validation.ts
Labels: 📖HTML&CSS, 🔨BugFix

#217 [철균] - #211 [fix] : 배포주소 구글소셜로그인 및 채팅방 높이조정
  src/app/globals.css
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/ListMessages.tsx
  src/utils/api/authAPI.ts
Labels: 🖥Feature, 🔨BugFix

#223 [승희]: 자유게시판 글 목록 유저프로필 캐시 제거, 글 목록 높이 유동적으로 변경, 인풋 확장자 제한
  src/components/myclubinfo2/board/Board.tsx
  src/components/myclubinfo2/board/posting/PhotoSection.tsx
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring

#224 [대연] - [fix]현재url기준으로 푸터 클릭화면 변경,종료하기 모달시 타이머 중지, 모달상태 zustand추가, 잘못 사용된 코드 변경
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/EndButton.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
  src/app/(navigationBar)/readbook/page.tsx
  src/components/footer/page.tsx
  src/store/modalstore.ts
Labels: 📖HTML&CSS, 🔨BugFix

#228 [대연] - #225 [design] - 푸터 border말구 그림자로 상단변경
  src/components/footer/page.tsx
Labels: 📖HTML&CSS

#235 [철균] - 채팅방 club thumbnail없을때 기본이미지로 thumbnail넣기, 위치조정
  public/bookbookddakgi.png
  src/app/chat/[id]/ChatInput.tsx
  src/app/globals.css
  src/components/login/LoginForm.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
Labels: 🖥Feature, 🔨BugFix

#239 Dev
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/EndButton.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
  src/components/mypage/profile/Profile.tsx
  src/hooks/usePostDataEffect.ts
  src/hooks/useRealtimePostgresChanges.ts
  src/store/index.ts
Labels: ✔Deploy

#240 [철균]-채팅창 더보기누르면10개씩더나오는기능, 폰트추가
  src/app/globals.css
  src/components/myclubinfo2/SentenceStorage.tsx
  src/components/myclubinfo2/SentenceUser.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/LoadMoreMessages.tsx
  src/lib/constant/index.ts
  src/lib/utils.ts
  src/store/InitMessages.tsx
  src/store/messages.ts
Labels: 🖥Feature, 🔨BugFix

#249 #248 [fix]-마이페이지에 있을 때 알람 뜨는지 테스트
  src/components/mypage/profile/Profile.tsx
Labels: ✔Deploy, 🔨BugFix

#252 [대연] #251 [fix]-layout테스트
  src/app/(navigationBar)/mypage/layout.tsx
  src/components/mypage/profile/Profile.tsx
Labels: 🔨BugFix

#253 [fix]-layout테스트
  src/app/(navigationBar)/mypage/layout.tsx
  src/components/mypage/profile/Profile.tsx
Labels: ✔Deploy

#255 [철균] - 불필요 import제거 및 주석추가
  src/app/chat/[id]/page.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/LoadMoreMessages.tsx
  src/lib/constant/index.ts
  src/store/InitMessages.tsx
  src/utils/supabase/middleware.ts
Labels: 🔨BugFix

#257 [대연] - #251 타임아웃 1초에서 3초로 변경하고 테스트
  src/app/(navigationBar)/mypage/layout.tsx
Labels: 🔨BugFix

#259 [철균] - 로그인하지않을때 페이지 이동을막음(middleware수정)
  src/app/login/action.ts
  src/middleware.ts
  src/utils/middlewares/authToken.ts
  src/utils/middlewares/chain.ts
  src/utils/middlewares/middleware.ts
  src/utils/middlewares/protectRoute.ts
Labels: 🖥Feature

#262 [예린] - 디자인 수정 및 에러 해결
  src/app/(navigationBar)/my-clubs/[clubId]/info/page.tsx
  src/app/(navigationBar)/mypage/mybookclubs/page.tsx
  src/app/(navigationBar)/mypage/page.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/components/my-clubs/info/ClubBook.tsx
  src/components/my-clubs/info/HomeTab.tsx
  src/components/mypage/clubs/AllMyBookClubs.tsx
  src/components/mypage/clubs/BookClubItem.tsx
  src/components/mypage/clubs/MyBookClub.tsx
  src/components/mypage/profile/LogoutButton.tsx
  src/components/mypage/profile/Profile.tsx
  src/components/mypage/profile/ProfileDetail.tsx
  src/components/mypage/sentences/AllMySentences.tsx
  src/components/mypage/sentences/MySentencesStore.tsx
  src/components/mypage/sentences/SentenceItem.tsx
  src/utils/userAPIs/storageAPI.ts
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring

#264 [철균]-#263 [fix]: 배포,로컬둘다 소셜로그인
  src/components/login/LoginForm.tsx
  src/utils/api/authAPI.ts
  src/utils/getCallBackURL.ts
Labels: 🔨BugFix

#281 [대연] -#272책 읽기 페이지 버튼 되돌리기,북클럽 책 읽기 버튼 클릭 후 화면에 멤버카드가 늦게 나타날때 빈 멤버카드 출력,readbook.페이지 join으로 리팩토링
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/page.tsx
  src/components/footer/page.tsx
Labels: 📖HTML&CSS, 🎨refactoring

#292 [철균]-#291 [fix] : storage 파일네임으로 변경
  src/app/register/set-profile-image/page.tsx
  src/components/mypage/profile/Profile.tsx
  src/utils/getCallBackURL.ts
  src/utils/userAPIs/storageAPI.ts
Labels: 🔨BugFix

#296 [철균]-Feature/#291
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/page.tsx
  src/components/realtime/OtherMessage.tsx
  src/lib/constant/index.ts
Labels: 🔨BugFix

#301 [대연] - #277 [fix]-책 저장페이지 입력할때마다 프로그레스바 반영 (수정중)
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveProgressBar.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
Labels: 🖥Feature, 🔨BugFix

#305 [철균]-문장저장소 저장버튼 disabled활성화
  src/app/(navigationBar)/my-clubs/[clubId]/sentences/page.tsx
  src/components/my-clubs/sentences/SentenceModal.tsx
  src/components/my-clubs/sentences/SentenceStorage.tsx
  src/components/my-clubs/sentences/SentenceUser.tsx
Labels: 🎨refactoring

#313 Dev
  src/app/(navigationBar)/layout.tsx
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/ReadButton.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/components/navigationBar/page.tsx
  src/lib/types/supabase.ts
Labels: ✔Deploy

#314 #277
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
Labels: 🖥Feature, 🔨BugFix

#318 [대연]-#277 [fix] - 책읽기페이지 모바일 환경에서 버튼 안보이는 현상 수정,[fix] - 콘솔삭제
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
Labels: 📖HTML&CSS

#328 [철균]-#327 [rafactor]: 자유게시판 fixed넓이조정및 소셜로그인(배포,local)
  src/app/(navigationBar)/my-clubs/[clubId]/posts/board/posting/[postId]/page.tsx
  src/components/my-clubs/board/boardDetail/BoardDetailArticle.tsx
  src/utils/api/authAPI.ts
  src/utils/getCallBackURL.ts
Labels: 🎨refactoring

#330 [철균]-#327 [fix]:배포로 재설정
  src/utils/api/authAPI.ts
  src/utils/getCallBackURL.ts
Labels: 🔨BugFix

#339 [대연] - [fix] - 10분이내에 재 모임시작시 alert->toast로 변경 , 공통 컴포넌트toast : duration prop으로 받게 변경 , archive true되었을 때, alert창 toastui로 변경
  src/app/(navigationBar)/bookclubs/layout.tsx
  src/app/(navigationBar)/my-clubs/layout.tsx
  src/app/(navigationBar)/mypage/layout.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/page.tsx
  src/common/ToastUi.tsx
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring

#341 [철균]-#327 [fix]: ToastUi duration수정
  src/components/login/LoginForm.tsx
  src/components/my-clubs/sentences/SentenceModal.tsx
  src/components/register/RegisterForm.tsx
Labels: 🔨BugFix

#343 [대연] - #340 [design] - 이미지 변경
  public/readbook_completed_read.png
  public/readbook_noclub.png
  public/readbook_yet_read.png
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/page.tsx
Labels: 📖HTML&CSS

#345 [승희] - post detail 페이지 레이아웃 안뜨게 변경, 스타일 변경
  src/app/(navigationBar)/board/detail/[postId]/page.tsx
  src/app/(navigationBar)/board/posting/[postId]/page.tsx
  src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
  src/components/my-clubs/board/Board.tsx
  src/components/my-clubs/board/boardDetail/ArticleCommentInput.tsx
  src/components/my-clubs/board/boardDetail/BoardDetailArticle.tsx
Labels: 📖HTML&CSS, 🎨refactoring

#357 [철균]-#342 [rafactor]: login폼 toastUI->validate
  src/app/login/page.tsx
  src/common/Input.tsx
  src/components/login/LoginForm.tsx
  src/utils/api/authAPI.ts
Labels: 🎨refactoring

#363 [대연] - #356 [fix]- input창 스크롤,음수 입력 방지,prefetch추가, 그만 읽기 클릭시 타이머 페이지 이동전까지 모달창 유지,책 읽기버튼시 로딩표기, 저장페이지 새로고침추가[mod] - 콘솔창에 나타나는 warning 안뜨게 수정 [design] - 멤버 스타일 grid로 변경
  src/app/(navigationBar)/bookclubs/layout.tsx
  src/app/(navigationBar)/my-clubs/layout.tsx
  src/app/(navigationBar)/mypage/layout.tsx
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/ReadButton.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/components/navigationBar/page.tsx
  src/hooks/usePostDataEffect.ts
  src/store/index.ts
  src/store/modalstore.ts
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring

#367 [철균]-Feature/#358
  src/app/(navigationBar)/bookclubs/create/page.tsx
  src/app/auth/authAPI.ts
Labels: 🎨refactoring

#377 [철균]- Feature/#375
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/components/login/LoginForm.tsx
  src/components/register/RegisterForm.tsx
  src/utils/api/authAPI.ts
Labels: 🎨refactoring

#385 #384 [design]-북클럽 방장이 책 읽기 시작시 멤버들에게 알림간다고 toast, 모달창 높이수정
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
Labels: 📖HTML&CSS

#392 [철균]-Feature/#375
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/app/chat/[id]/page.tsx
  src/components/realtime/ChatInfo.tsx
Labels: 🎨refactoring

#396 [rafactor]: chatting 탭으로 변경 [rafactor]:탭 width 1/3로바꿈 [fix]:닉네임 띄어쓰기 막기
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/app/chat/[id]/page.tsx
  src/components/mypage/profile/ProfileDetail.tsx
  src/components/realtime/ChatInfo.tsx
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring

#399 #389 [fix]-타이머 1:00:00->0:00:00 내려가게 수정,0:00:00때 완료모달, 책 읽기 다시시작하면 1:00:00으로 다시 스타트
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/CompleteModal.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
  src/app/chat/[id]/ChatInput.tsx
  src/store/messages.ts
Labels: 🖥Feature, 🔨BugFix, 🎨refactoring

#404 북클럽info에 요일추가,[design]-디자인수정,[fix]-모달상태리셋추가,[mod]-변수명변경
  src/app/(navigationBar)/mypage/mybookclubs/page.tsx
  src/app/(navigationBar)/mypage/mysentences/page.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/EndButton.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/page.tsx
  src/components/my-clubs/info/HomeTab.tsx
  src/components/mypage/profile/ProfileDetail.tsx
  src/store/modalstore.ts
Labels: 🔨BugFix, 🎨refactoring

#405 [승희]: my-clubs 페이지의 getUser함수 요청 줄이기
  src/app/(navigationBar)/bookclubs/layout.tsx
  src/app/(navigationBar)/my-clubs/layout.tsx
  src/components/my-clubs/board/Board.tsx
  src/components/my-clubs/info/ClubBook.tsx
  src/hooks/info/useMyClubInfo.tsx
  src/utils/userAPIs/authAPI.ts
Labels: 🎨refactoring, 💻API

#407 [refactor]: 문장가져오는부분 join으로변경함
  src/components/mypage/sentences/AllMySentences.tsx
  src/components/mypage/sentences/MySentencesStore.tsx
  src/components/mypage/sentences/SentenceItem.tsx
  src/hooks/mypage/useUserSentences.tsx
Labels: 🎨refactoring

#410 [main] - 변경사항 적용
  src/app/(navigationBar)/bookclubs/layout.tsx
  src/app/(navigationBar)/my-clubs/layout.tsx
  src/components/my-clubs/board/Board.tsx
  src/components/my-clubs/info/ClubBook.tsx
  src/components/mypage/sentences/AllMySentences.tsx
  src/components/mypage/sentences/MySentencesStore.tsx
  src/components/mypage/sentences/SentenceItem.tsx
  src/hooks/info/useMyClubInfo.tsx
  src/hooks/mypage/useUserSentences.tsx
  src/utils/userAPIs/authAPI.ts
Labels: 📖HTML&CSS, 🔨BugFix, 🎨refactoring, 💻API

#411 [철균]-#393 [rafactor]:채팅tab다시 css구현및 리팩토링
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/chat/[id]/ChatInput.tsx
  src/app/globals.css
  src/components/realtime/ChatBackImg.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/OtherMessage.tsx
Labels: 📖HTML&CSS, 🎨refactoring

#412 Dev
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/chat/[id]/ChatInput.tsx
  src/app/globals.css
  src/components/realtime/ChatBackImg.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/OtherMessage.tsx
Labels: 🎨refactoring

#422 [승희]: readbook [id]페이지 성능 개선
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/utils/testAPIs.ts
  src/utils/userAPIs/authAPI.ts
Labels: 🎨refactoring, 💻API

#426 [대연]-#408 [fix]-슬라이드버그수정, 멤버색깔수정,[refactor]:join바꿔보기
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/ReadButton.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
Labels: 🔨BugFix, 🎨refactoring

#437 [design]:mb-4수정
  src/components/my-clubs/info/ClubBook.tsx
Labels: 📖HTML&CSS

#438 [design]: mb-4추가함
  .vscode/extensions.json
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/app/chat/[id]/ChatInput.tsx
  src/app/chat/[id]/page.tsx
  src/components/my-clubs/info/ClubBook.tsx
  src/components/realtime/ChatBackImg.tsx
  src/components/realtime/ChatInfo.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ListMessages.tsx
  src/components/realtime/LoadMoreMessages.tsx
  src/components/realtime/OtherMessage.tsx
  src/store/messages.ts
Labels: 📖HTML&CSS

#453 [design,refactor]:애니메이션 추가
  package.json
  public/animation.json
  src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
  src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
  src/app/(navigationBar)/my-clubs/page.tsx
  src/components/common/Animation.tsx
  src/components/mypage/profile/ProfileDetail.tsx
  src/hooks/info/useMyClubInfo.tsx
  yarn.lock
Labels: 📖HTML&CSS, 🎨refactoring

#456 [승희] - **중요** PWA 적용 (metadata, manifest 있음)
  next.config.js
  package.json
  public/192.png
  public/android-launchericon-512-512.png
  public/manifest.json
  public/sw.js
  public/workbox-c06b064f.js
  src/app/layout.tsx
  yarn.lock
Labels: 🖥Feature, 🎨refactoring

#459 [대연] - #408 [fix] - 네트워크탭 user요청 줄이기,이미지 priority넣기
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/(navigationBar)/readbook/ClubList.tsx
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/EndModal.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveBookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/SaveCard.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/Timer.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/app/(navigationBar)/readbook/page.tsx
Labels: 🔨BugFix, 🎨refactoring

#460 [철균]-채팅창파일첨부
  src/app/chat/[id]/ChatInput.tsx
  src/components/realtime/ChatBackImg.tsx
  src/components/realtime/ChatPresence.tsx
  src/components/realtime/Message.tsx
  src/components/realtime/OtherMessage.tsx
  src/lib/types/supabase.ts
  src/store/messages.ts
Labels: 🖥Feature

#469 [design]:로딩크기 수정
  public/sw.js.map
  src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
  src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
  src/app/(navigationBar)/my-clubs/page.tsx
  src/app/globals.css
  src/components/mypage/profile/ProfileDetail.tsx
Labels: 📖HTML&CSS

#470 [대연] - #408 [feat]-로딩gif적용,[fix]-any타입 변경,이미지priority설정
  public/sw.js.map
  public/로딩.gif
  src/app/(navigationBar)/readbook/[id]/BookInfo.tsx
  src/app/(navigationBar)/readbook/[id]/MemberList.tsx
  src/app/(navigationBar)/readbook/[id]/[save]/page.tsx
  src/app/(navigationBar)/readbook/[id]/page.tsx
  src/app/(navigationBar)/readbook/page.tsx
  src/components/common/Loading.tsx
Labels: 🖥Feature

#479 [fix]: prefetch 도입
  public/sw.js.map
  src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
  src/components/navigationBar/page.tsx
Labels: 🎨refactoring

#480 [승희] - prefetch 넣음
  public/sw.js.map
  src/app/(navigationBar)/my-clubs/[clubId]/layout.tsx
  src/app/login/action.ts
  src/components/navigationBar/page.tsx
  src/components/realtime/ChatBackImg.tsx
  src/components/realtime/ChatInfo.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ChatPresence.tsx
Labels: 🎨refactoring

#481 [철균]-상대프로필화면수정(채팅)
  public/sw.js.map
  src/components/realtime/OtherMessage.tsx
Labels: 🎨refactoring

#483 [철균]-#482 [fix,refactor] 소셜로그인 pointer추가 및 채팅애니메이션추가
  public/sw.js.map
  src/app/globals.css
  src/components/login/LoginForm.tsx
  src/components/realtime/Message.tsx
  src/components/realtime/OtherMessage.tsx
Labels: 🔨BugFix, 🎨refactoring

#486 [승희]: 스플래시 화면 추가
  public/logo_white.png
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/loading.tsx
Labels: 🔊help wanted

#489 [design]: 북클럽 탈퇴하가, 북클럽 이동하기 모달만들기
  public/Resign.svg
  public/sw.js
  src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
  src/app/globals.css
  src/components/my-clubs/info/HomeTab.tsx
  src/components/my-clubs/info/ResignBtn.tsx
  src/components/my-clubs/info/ResignModal.tsx
  src/components/my-clubs/info/SelectModal.tsx
  src/components/my-clubs/info/WithdrawalPopup.tsx
Labels: 📖HTML&CSS

#493 [철균]-#492 [feat]:서스팬스,온보딩추가
  public/onboarding1.svg
  public/onboarding3.svg
  public/onboarding4.svg
  public/sw.js
  public/workbox-c06b064f.js
  src/app/globals.css
  src/app/loading.tsx
  src/app/page.tsx
  src/components/common/Splash.tsx
  src/components/register/OnboardingPage.tsx
Labels: 🖥Feature

#495 [fix]-방장탈퇴못하게함
  public/sw.js
  src/components/my-clubs/info/ResignModal.tsx
  src/components/my-clubs/info/WithdrawalPopup.tsx
Labels: 🔨BugFix

#500 #499 [fix]: 종료된 북클럽들어갔을때처리
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
  src/app/(navigationBar)/my-clubs/page.tsx
  src/app/globals.css
  src/components/my-clubs/info/HomeTab.tsx
  src/components/my-clubs/info/ResignModal.tsx
  src/components/my-clubs/info/SelectModal.tsx
  src/components/my-clubs/info/WithdrawalPopup.tsx
  src/hooks/info/useMyClubInfo.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#501 마이페이지에서 종료된 북클럽들어갔을때처리
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/(navigationBar)/my-clubs/[clubId]/ClubSelector.tsx
  src/app/(navigationBar)/my-clubs/page.tsx
  src/app/globals.css
  src/components/my-clubs/info/HomeTab.tsx
  src/components/my-clubs/info/ResignModal.tsx
  src/components/my-clubs/info/SelectModal.tsx
  src/components/my-clubs/info/WithdrawalPopup.tsx
  src/hooks/info/useMyClubInfo.tsx
Labels: 📖HTML&CSS, 🔨BugFix

#509 redirect수정
  public/256.png
  public/manifest.json
  public/sw.js.map
  public/workbox-c06b064f.js
  src/app/chat/[id]/page.tsx
  src/app/login/page.tsx
  src/components/realtime/ChatMessages.tsx
  src/components/realtime/ListMessages.tsx
  src/utils/api/authAPI.ts
Labels: 🎨refactoring

#513 [fix]: 종료된 북클럽일때 문장저장, 글쓰기 저장 버튼 막기
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/(navigationBar)/my-clubs/[clubId]/sentences/page.tsx
  src/components/my-clubs/board/Board.tsx
  src/components/my-clubs/sentences/SentenceStorage.tsx
  src/utils/userAPIs/authAPI.ts
Labels: 🔨BugFix

#514 [fix]:종료된 북클럽일때 문장저장, 글쓰기 버튼 없애기
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/(navigationBar)/my-clubs/[clubId]/sentences/page.tsx
  src/components/my-clubs/board/Board.tsx
  src/components/my-clubs/sentences/SentenceStorage.tsx
  src/utils/userAPIs/authAPI.ts
Labels: 🔨BugFix

#516 자유게시판 border-t없애기
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/components/my-clubs/board/Board.tsx
Labels: 📖HTML&CSS
